In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [2]:
# data contoh
data = np.array([[2.0, 5.0],
                 [1.0, 4.0],
                 [3.0, 6.0]])

# inisialisasi objek minmaxscaler
scaler = MinMaxScaler()

# fit dan transformasi data menggunakan min-max scaling
scaled_data = scaler.fit_transform(data)

print("Data Asli: ")
print(data)

print("\nData setelah di Min-Max Scaling: ")
print(scaled_data)

Data Asli: 
[[2. 5.]
 [1. 4.]
 [3. 6.]]

Data setelah di Min-Max Scaling: 
[[0.5 0.5]
 [0.  0. ]
 [1.  1. ]]


In [3]:
# data contoh
data = np.array([[2.0, 5.0],
                 [1.0, 4.0],
                 [3.0, 6.0]])

# inisialisasi objek standardscaler
scaler = StandardScaler()

# fit dan transformasi data menggunakan z-score transformation
z_score_data = scaler.fit_transform(data)

print("Data Asli: ")
print(data)

print('\nData Setelah Z-Score Transformation: ')
print(z_score_data)

Data Asli: 
[[2. 5.]
 [1. 4.]
 [3. 6.]]

Data Setelah Z-Score Transformation: 
[[ 0.          0.        ]
 [-1.22474487 -1.22474487]
 [ 1.22474487  1.22474487]]


In [4]:
# data contoh
data = np.array([200, 300, 400, 500, 600])

# menentukan faktor penggeseran (scaling factor),
# misal 1000 untuk mengubah ke rentang 0-1
scaling_factor = 1000

# melakukan transformasi decimal scaling
scaled_data = data / scaling_factor

print("Data Asli: ")
print(data)

print('\nData Setelah Decimal Transformation: ')
print(scaled_data)

Data Asli: 
[200 300 400 500 600]

Data Setelah Decimal Transformation: 
[0.2 0.3 0.4 0.5 0.6]
